// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa_XEa0COXLSrs7SG2QbPRaomrqx9Su4E',
    appId: '1:746172202585:web:13eb5be7626605e22dfb48',
    messagingSenderId: '746172202585',
    projectId: 'todonew-59a3b',
    authDomain: 'todonew-59a3b.firebaseapp.com',
    databaseURL: 'https://todonew-59a3b-default-rtdb.firebaseio.com',
    storageBucket: 'todonew-59a3b.appspot.com',
    measurementId: 'G-J2Q89VMT02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRH4J7R1vfBUeP2ncCf9FKhU4NuqBF2I',
    appId: '1:746172202585:android:40b45a98e78032602dfb48',
    messagingSenderId: '746172202585',
    projectId: 'todonew-59a3b',
    databaseURL: 'https://todonew-59a3b-default-rtdb.firebaseio.com',
    storageBucket: 'todonew-59a3b.appspot.com',
  );
}
